- README.md
- main.tf
replaces PR #12
Closes Issue #11
> Add Azure Container Registry

- README.md
- examples/default/README.md
- examples/default/main.tf
- examples/with_availability_zone/README.md
- examples/with_availability_zone/main.tf
- examples/without_availability_zone/README.md
- examples/without_availability_zone/main.tf
- locals.tf
- main.tf
- terraform.tf
- variables.tf
Handles automatic upgrades by AKS patch channel correctly
> Implement automatic upgrades in patch channel

- README.md
- examples/default/README.md
- examples/default/main.tf
- main.tf
- variables.tf
Fixes #28
The user optionally can specify `node_cidr` and `pod_cidr`. The VNET is created in the module so that is stay in the user resource group.
> Implement Bring Your Own Network

- README.md
- examples/default/README.md
- examples/default/main.tf
- examples/default/variables.tf
- locals.tf
- main.tf
Fixes #24 
Force always the use of UserAssigned identity.
Enable monitor metrics
> Remove dynamic blocks

- README.md
- main.tf
- variables.tf
Enable login with microsoft entra
> Enable login with microsoft entra

- README.md
- main.tf
> Drop unused datasource

- locals.tf
add ContainerLogV2 to log_analytics_tables
#23
> add ContainerLogV2 to log_analytics_tables

- README.md
- examples/default/README.md
- examples/with_availability_zone/README.md
- examples/with_availability_zone/main.tf
- examples/without_availability_zone/README.md
- examples/without_availability_zone/main.tf
- locals.tf
- main.tf
- variables.tf
The builds are currently failing because of new avm standards introduced in regards to interfaces 
https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#tags
This affects tags, managed_identities and lock
> fix failing build by adopting avm standards

- README.md
- _header.md
> add instructions to readme

- README.md
- variables.tf
Removes an unused variable. Fixes #56
> Drop unused variable log_analytics_workspace_id

- examples/default/README.md
- examples/default/main.tf
- examples/with_availability_zone/README.md
- examples/with_availability_zone/main.tf
- main.tf
fixes the currently broken pipeline
> Fix default value for max surge

- main.tf
> Update Microsoft.ContainerService API version in azapi resource

- README.md
- terraform.tf
Improve provider versions constraint as discussed with @lonegunmanb
> Improve provider version constraints

- README.md
- locals.tf
- main.tf
- variables.tf
Adds Node Labels to all nodepools.
Closes #106
> Add Node Labels

- README.md
- locals.tf
- main.tf
Add necessary role assignment to fix #102
Closes #102 
- [ X] Bugfix containing backwards compatible bug fixes
> assign Network Contributor role to AKS identities

- main.tf
Disable local accounts
Fixes #114
Closes #114
-->
> Disable local accounts

- README.md
- examples/default/README.md
- examples/default/main.tf
- main.tf
- variables.tf
leverage the AVM container registry module and private link
Fixes #115
Closes #115
-->
> leverage the AVM container registry module and private link

- README.md
- examples/default/README.md
- examples/default/main.tf
- examples/with_availability_zone/README.md
- examples/with_availability_zone/main.tf
- examples/without_availability_zone/README.md
- examples/without_availability_zone/main.tf
- main.tf
- variables.tf
Create the Vnet and the subnets outside of this module.
Make the ACR optional, but if present must be with private link.
Fixes #112 
Closes #112 
-->
> Create the Vnet and the subnets outside of this module

- README.md
- _header.md
> Correction on README - we dont create the vnet

- main.tf
#150 
- [x ] Azure Verified Module updates:
- [ x] Bugfix containing backwards compatible bug fixes
- [ x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
> Add cilium as the option for network policy

- README.md
- main.tf
- variables.tf
Closes #149 
- [ x] Azure Verified Module updates:
- [x ] Bugfix containing backwards compatible bug fixes
- [ x] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
- [x ] I'm sure there are no other open Pull Requests for the same update/change
- [ x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x ] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks
> add service cidr

- README.md
- examples/default/README.md
- examples/default/main.tf
- examples/with_availability_zone/README.md
- examples/with_availability_zone/main.tf
- examples/without_availability_zone/README.md
- examples/without_availability_zone/main.tf
- locals.tf
- main.tf
- variables.tf
Add missing `dns_service_ip` and set a default if it needs it and not supplied.
Fixes #180
> fix: missing network setting
